kind: pipeline
name: dev

trigger:
  branch:
    - dev

clone:
  disable: true

steps:
  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0

  - name: charts
    image: registry.cn-qingdao.aliyuncs.com/wod/helm:v3
    commands:
    - cp .beagle/values-amd64.yaml ./deployments/gpu-operator/
    - helm package ./deployments/gpu-operator

  - name: minio-charts
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-minio:1.0
    environment:
      S3_ACCESS_KEY:
        from_secret: ACCESS_KEY_MINIO
      S3_SECRET_KEY:
        from_secret: SECRET_KEY_MINIO
    commands:
      - mc alias set aliyun --api=S3v4 https://cache.wodcloud.com $S3_ACCESS_KEY $S3_SECRET_KEY
      - mc cp gpu-operator-v1.0.0-devel.tgz aliyun/kubernetes/cps/gpu-operator/gpu-operator-v1.0.0-devel.tgz
  
  - name: images-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-images:1.0
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod
      yaml: .beagle/images.yaml
      image: images
      group: wod
      release: .tmp/amd64/images-nvidia-gpu-operator-v1.0.0-devel.tgz

  - name: minio-images
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-minio:1.0
    environment:
      S3_ACCESS_KEY:
        from_secret: ACCESS_KEY_MINIO
      S3_SECRET_KEY:
        from_secret: SECRET_KEY_MINIO
    commands:
      - mc alias set aliyun --api=S3v4 https://cache.wodcloud.com $S3_ACCESS_KEY $S3_SECRET_KEY
      - mc cp .tmp/amd64/images-nvidia-gpu-operator-v1.0.0-devel.tgz aliyun/kubernetes/cps/gpu-operator/images-nvidia-gpu-operator-v1.0.0-devel.tgz

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets