validator:
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia
  version: gpu-operator-validator-v24.9.2

operator:
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia
  version: gpu-operator-v24.9.2
  initContainer:
    repository: registry.cn-qingdao.aliyuncs.com/wod
    image: nvidia
    version: cuda-12.6.3-base-ubi9
  resources:
    limits:
      memory: 350Mi
    requests:
      memory: 100Mi

driver:
  enabled: false
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia-driver
  version: "570.124.06"
  manager:
    repository: registry.cn-qingdao.aliyuncs.com/wod
    image: nvidia
    version: k8s-driver-manager-v0.7.0

toolkit:
  enabled: true
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia
  version: container-toolkit-v1.17.4-ubuntu20.04

devicePlugin:
  enabled: true
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia
  version: k8s-device-plugin-v0.17.0
  config:
    name: device-plugin-config
    create: true
    data:
      default: |-
        version: v1
        flags:
          migStrategy: none
          failOnInitError: true
          nvidiaDriverRoot: "/"
          plugin:
            passDeviceSpecs: false
            deviceListStrategy: envvar
            deviceIDStrategy: uuid
      mig-single: |-
        version: v1
        flags:
          migStrategy: single
      mig-mixed: |-
        version: v1
        flags:
          migStrategy: mixed
      time-2: |-
        version: v1
        sharing:
          renameByDefault: true
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 2
      time-3: |-
        version: v1
        sharing:
          renameByDefault: true
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 3
      time-4: |-
        version: v1
        sharing:
          renameByDefault: true
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 4
      time-5: |-
        version: v1
        sharing:
          renameByDefault: true
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 5
      time-6: |-
        version: v1
        sharing:
          renameByDefault: true
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 6
      time-7: |-
        version: v1
        sharing:
          renameByDefault: true
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 7
      time-8: |-
        version: v1
        sharing:
          renameByDefault: true
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 8

dcgmExporter:
  enabled: true
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia
  version: dcgm-exporter-3.3.9-3.6.1-ubuntu22.04

gfd:
  enabled: true
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia
  version: k8s-device-plugin-v0.17.0

migManager:
  enabled: true
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia
  version: k8s-mig-manager-v0.10.0-ubuntu20.04

nodeStatusExporter:
  enabled: true
  repository: registry.cn-qingdao.aliyuncs.com/wod
  image: nvidia
  version: gpu-operator-validator-v24.9.2

gds:
  enabled: false

gdrcopy:
  enabled: false

vgpuManager:
  enabled: false

vgpuDeviceManager:
  enabled: false

vfioManager:
  enabled: false

kataManager:
  enabled: false

sandboxDevicePlugin:
  enabled: false

ccManager:
  enabled: false

node-feature-discovery:
  image:
    repository: registry.cn-qingdao.aliyuncs.com/wod/nvidia
    tag: node-feature-discovery-v0.16.6
  master:
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 0
        memory: 128Mi
  worker:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 0
        memory: 64Mi
  gc:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 0
        memory: 128Mi
        