name: Build and Push Docker Images

on:
  push:
    branches:
      - dev

jobs:
  build-gpu-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build gpu-operator
        run: bash .beagle/build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.beagle/dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:v24.9.2
            registry.cn-qingdao.aliyuncs.com/wod/nvidia:gpu-operator-v24.9.2
          platforms: linux/amd64
          build-args: |
            BASE=nvcr.io/nvidia/cuda:12.6.3-base-ubi9
            AUTHOR=${{ github.repository_owner }}
            VERSION=v24.9.2

      - name: gpu-operator-validator
        run: |
          docker pull nvcr.io/nvidia/cloud-native/gpu-operator-validator:v24.9.2 && \
          docker tag nvcr.io/nvidia/cloud-native/gpu-operator-validator:v24.9.2 registry.cn-qingdao.aliyuncs.com/wod/nvidia:gpu-operator-validator-v24.9.2 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:gpu-operator-validator-v24.9.2

      - name: cuda
        run: |
          docker pull nvcr.io/nvidia/cuda:12.6.3-base-ubi9 && \
          docker tag nvcr.io/nvidia/cuda:12.6.3-base-ubi9 registry.cn-qingdao.aliyuncs.com/wod/nvidia:cuda-12.6.3-base-ubi9 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:cuda-12.6.3-base-ubi9

      - name: dcgm-exporter
        run: |
          docker pull nvcr.io/nvidia/k8s/dcgm-exporter:3.3.9-3.6.1-ubuntu22.04 && \
          docker tag nvcr.io/nvidia/k8s/dcgm-exporter:3.3.9-3.6.1-ubuntu22.04 registry.cn-qingdao.aliyuncs.com/wod/nvidia:dcgm-exporter-3.3.9-3.6.1-ubuntu22.04 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:dcgm-exporter-3.3.9-3.6.1-ubuntu22.04

      - name: container-toolkit
        run: |
          docker pull nvcr.io/nvidia/k8s/container-toolkit:v1.17.4-ubuntu20.04 && \
          docker tag nvcr.io/nvidia/k8s/container-toolkit:v1.17.4-ubuntu20.04 registry.cn-qingdao.aliyuncs.com/wod/nvidia:container-toolkit-v1.17.4-ubuntu20.04 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:container-toolkit-v1.17.4-ubuntu20.04

      - name: driver
        run: |
          docker pull nvcr.io/nvidia/driver:570.124.06-ubuntu24.04 && \
          docker tag nvcr.io/nvidia/driver:570.124.06-ubuntu24.04 registry.cn-qingdao.aliyuncs.com/wod/nvidia:driver-570.124.06-ubuntu24.04 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:driver-570.124.06-ubuntu24.04 && \
          docker tag nvcr.io/nvidia/driver:570.124.06-ubuntu24.04 registry.cn-qingdao.aliyuncs.com/wod/nvidia:driver-570.124.06-debian12 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:driver-570.124.06-debian12
          
      - name: node-feature-discovery
        run: |
          docker pull registry.k8s.io/nfd/node-feature-discovery:v0.16.6 && \
          docker tag registry.k8s.io/nfd/node-feature-discovery:v0.16.6 registry.cn-qingdao.aliyuncs.com/wod/nvidia:node-feature-discovery-v0.16.6 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:node-feature-discovery-v0.16.6

      - name: k8s-driver-manager
        run: |
          docker pull nvcr.io/nvidia/cloud-native/k8s-driver-manager:v0.7.0 && \
          docker tag nvcr.io/nvidia/cloud-native/k8s-driver-manager:v0.7.0 registry.cn-qingdao.aliyuncs.com/wod/nvidia:k8s-driver-manager-v0.7.0 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:k8s-driver-manager-v0.7.0

      - name: k8s-device-plugin
        run: |
          docker pull nvcr.io/nvidia/k8s-device-plugin:v0.17.0 && \
          docker tag nvcr.io/nvidia/k8s-device-plugin:v0.17.0 registry.cn-qingdao.aliyuncs.com/wod/nvidia:k8s-device-plugin-v0.17.0 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:k8s-device-plugin-v0.17.0

      - name: k8s-mig-manager
        run: |
          docker pull nvcr.io/nvidia/cloud-native/k8s-mig-manager:v0.10.0-ubuntu20.04 && \
          docker tag nvcr.io/nvidia/cloud-native/k8s-mig-manager:v0.10.0-ubuntu20.04 registry.cn-qingdao.aliyuncs.com/wod/nvidia:k8s-mig-manager-v0.10.0-ubuntu20.04 && \
          docker push registry.cn-qingdao.aliyuncs.com/wod/nvidia:k8s-mig-manager-v0.10.0-ubuntu20.04

      - name: Image push success
        run: echo "Docker image pushed successfully to ghcr.io/${{ github.repository }}:v24.9.2"
