name: Build and Push Docker Images

on:
  push:
    branches:
      - dev

jobs:
  build-nvidia-egl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build gpu-operator
        run: bash .beagle/build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.beagle/dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:v24.9.2
            registry.cn-qingdao.aliyuncs.com/wod/nvidia-gpu-operator:v24.9.2
          platforms: linux/amd64
          build-args: |
            BASE=nvcr.io/nvidia/cuda:12.6.3-base-ubi9
            AUTHOR=${{ github.repository_owner }}
            VERSION=v24.9.2

      - name: Image push success
        run: echo "Docker image pushed successfully to ghcr.io/${{ github.repository }}:v24.9.2"
